export const MESSAGING_NAMESPACE = "onlook-aa5d4a6b-d04d-4cb4-8476-3cc14241facd";

export enum MessageType {
    APPLY_PROJECT_CHANGE = "APPLY_PROJECT_CHANGE",

    DASHBOARD_SIGN_IN = "DASHBOARD_SIGN_IN",
    DASHBOARD_SIGN_OUT = "DASHBOARD_SIGN_OUT",

    EDIT_EVENT = "EDIT_EVENT",
    EDIT_PROJECT = "EDIT_PROJECT",

    GET_PROJECT = "GET_PROJECT",
    GET_PROJECTS = "GET_PROJECTS",
    GET_PAGE_SCREENSHOT = "GET_PAGE_SCREENSHOT",

    MERGE_PROJECT = "MERGE_PROJECT",
    OPEN_URL = "OPEN_URL",

    PUBLISH_PROJECT = "PUBLISH_PROJECT",
    PREPARE_SAVE = "PREPARE_SAVE",

    SEND_CHAT_MESSAGE = "SEND_CHAT_MESSAGE",
    SHOULD_TOUR = "SHOULD_TOUR",

    TOGGLE_EDITOR = "TOGGLE_EDITOR",
}
