version: '3.8'

services:
  client:
    build: ./client
    image: hoakiet98/onlook-client
    ports:
      - "8000:5173"
    depends_on:
      - server
    volumes:
      - client_files:/usr/src/app
      
  server:
    build: ./server
    image: hoakiet98/onlook-server
    ports: 
      - "8001:8080"
    volumes:
      - client_files:/usr/src/app/client

volumes:
  client_files: